APP_HOST_ENV_VAR = "APP_HOST"
APP_PORT_ENV_VAR = "APP_PORT"
APP_DEBUG_ENV_VAR = "APP_DEBUG"

DEFAULT_APP_HOST = "0.0.0.0"
DEFAULT_APP_PORT = 8080
DEFAULT_APP_DEBUG = False
DEFAULT_THREADED = True

LOCALHOST_VALUE = "localhost"
LOOPBACK_HOST = "127.0.0.1"
LOOPBACK_PREFIX = "127."
WILDCARD_HOSTS = frozenset(("0.0.0.0", "::"))

BOOLEAN_TRUE_VALUES = frozenset(("1", "true", "yes", "on"))
LAN_DISCOVERY_TARGET = ("8.8.8.8", 80)

STARTUP_SEPARATOR_SIZE = 60
